### ISSUE TITLE
Unknown or unsupported HipChat API version: [v2 ]

### ISSUE THREAD

**Issue by waqas29** [hbakkum/rundeck-hipchat-plugin#18]
Hi @hbakkum ,

@hbakkum I am trying to setup this plugin. But I am getting error v2 is unknows or not supported
when I specified following settings;

configure framework:
framework.plugin.Notification.HipChatNotification.apiVersion=v2
framework.plugin.Notification.HipChatNotification.apiAuthToken=value

configure project:
project.plugin.Notification.HipChatNotification.apiVersion=v2
project.plugin.Notification.HipChatNotification.apiAuthToken=value

Do you know why am I getting this?
Also on rundeck in hipchat section, you only specify room id and that's it right?

@hbakkum This is what I am getting:

class com.hbakkum.rundeck.plugins.hipchat.HipChatNotificationPluginException: Unknown or unsupported HipChat API version: [v2 ]

I am using new version of plugin 1.7.0.

Please let me know. Thanks

Regards,
Waqas.

**Comment by hbakkum** [comment]
Hey Waqas,

I'm thinking that you have a trailing space after the v2 in your rundeck properties file. I should probably be trimming this value. Can you check for a trailing space and remove it if its there.

Cheers,
Hayden

**Comment by waqas29** [comment]
@hbakkum Thank you, I will check and test it. 
Really appreciate your help. Thanks
